pages = [{"l":"api/index.html","n":"caliban-deriving","t":"caliban-deriving","d":"","k":"static"},
{"l":"api/caliban/deriving.html","n":"caliban.deriving","t":"package caliban.deriving","d":"caliban/deriving","k":"package"},
{"l":"api/caliban/deriving.html","n":"deriveSchemaInstance","t":"def deriveSchemaInstance[R, T]: Schema[R, T]","d":"caliban/deriving","k":"def"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"BuildInfo","t":"object BuildInfo","d":"caliban/deriving/BuildInfo$","k":"object"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"isSnapshot","t":"val isSnapshot: Boolean","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"moduleName","t":"val moduleName: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"name","t":"val name: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"organization","t":"val organization: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"sbtVersion","t":"val sbtVersion: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"scalaVersion","t":"val scalaVersion: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"toString","t":"val toString: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/BuildInfo$.html","n":"version","t":"val version: String","d":"caliban/deriving/BuildInfo$","k":"val"},
{"l":"api/caliban/deriving/annotations.html","n":"caliban.deriving.annotations","t":"package caliban.deriving.annotations","d":"caliban/deriving/annotations","k":"package"},
{"l":"api/caliban/deriving/annotations/GQLExclude.html","n":"GQLExclude","t":"class GQLExclude() extends StaticAnnotation","d":"caliban/deriving/annotations/GQLExclude","k":"class"},
{"l":"docs/index.html","n":"caliban-deriving","t":"caliban-deriving","d":"","k":"static"}];